---
- hosts: all
  become: true
  tasks:
    - name: Update Resolv.conf
      blockinfile:
        path: /etc/resolv.conf
        block: |
          nameserver 2001:558:feed::1
          nameserver 2001:558:feed::2
          nameserver 75.75.75.75
          nameserver 75.75.76.76
